import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import MotionProvider from "@/features/shared/components/motion-provider";

const centuryGothic = localFont({
  src: [
    {
      path: "../../public/fonts/centurygothic.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/centurygothic_bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-century-gothic",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"),
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${centuryGothic.variable}`}
    >
      <body >
        <MotionProvider>
          {children}
        </MotionProvider>
      </body>
    </html>
  );
}
