import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/features/shared/components/navbar";
import Footer from "@/features/shared/components/footer";

const centuryGothic = localFont({
  src: [
    {
      path: "../../public/fonts/centurygothic.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/centurygothic_bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-century-gothic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${centuryGothic.variable}`}
    >
      <body >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
